// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0r3eAVn9U8o2ivTOQON_h1dzhx_Qw7_g',
    appId: '1:490381772818:android:06993d68be46c1f337f0cb',
    messagingSenderId: '490381772818',
    projectId: 'firebasetest-121',
    databaseURL: 'https://firebasetest-121-default-rtdb.firebaseio.com',
    storageBucket: 'firebasetest-121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjGkmBCV7mtEJE2VvPYYrzhp7_iz8R6E',
    appId: '1:490381772818:ios:907e033e36d0039a37f0cb',
    messagingSenderId: '490381772818',
    projectId: 'firebasetest-121',
    databaseURL: 'https://firebasetest-121-default-rtdb.firebaseio.com',
    storageBucket: 'firebasetest-121.appspot.com',
    iosClientId: '490381772818-7tla6959nr3isu53dncooaf0jnoai0cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetestcrash',
  );
}
